# Change these first
owner: j1nxie # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: personal website
    url: https://rylie.moe
  - name: closure-api
    url: https://closure.rylie.moe/api/status
  - name: nazunacord chibisafe
    url: https://nazunacord.net/api/health
  - name: nazunacord jellyfin
    url: https://jellyfin.nazunacord.net/health

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: rylie.moe
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: uptime status
  introTitle: "status page for all my sites and services, hosted under the domains rylie.moe and nazunacord.net!"
  introMessage: everything that's personally hosted by me is tracked here! powered by [**upptime**](https://github.com/upptime/upptime).
  navbar:
    - title: status
      href: /
    - title: homepage
      href: https://rylie.moe
    - title: github
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
